GET http://localhost:5202/games

### 
GET http://localhost:5202/games/1

###
POST http://localhost:5202/games
Content-Type: application/json 

{
    "name":"Hola",
    "genreId":3,
    "price":20.00,
    "releaseDate":"2023-10-20"
} 

###
PUT http://localhost:5202/games/1 
Content-Type: application/json 

{
    "name":"GTA 5",
    "genreId":3,
    "price":50.00,
    "releaseDate":"2023-10-20"
} 

### 
DELETE http://localhost:5202/games/1 
Content-Type: application/json 